# Generated by Django 4.0.6 on 2022-07-19 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_rename_sub_headline_project_sub_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='headline',
        ),
    ]
