# Generated by Django 4.0.6 on 2022-07-19 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_rename_headline_project_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='thumbnail',
            new_name='front_page',
        ),
    ]
