# Generated by Django 4.0.6 on 2022-07-19 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_rename_thumbnail_project_front_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='active',
        ),
        migrations.RemoveField(
            model_name='project',
            name='featured',
        ),
    ]
